const cadastropim = require("../fixtures/cadastroUsuario.json");

describe('Cadastro de usuários na tela "PIM"', () => {

    beforeEach(() => {
    cy.login()
    cy.visit('/pim/viewEmployeeList')
  })

  it('Teste deve tentar cadastrar um usuário sem preencher os campos de nome', () => {
    cy.get('.orangehrm-header-container > .oxd-button').should('be.visible')
      .and('be.enabled')
      .click()
    cy.get('.oxd-button--secondary').as('clickSave').should('be.visible')
      .and('be.enabled')
      .click()

    cy.get('.orangehrm-card-container').should('not.be.disabled')
      .and('contain', 'Required')
  })

  it('Teste deve cadastrar um usuário corretamente', () => {
    cy.get('.orangehrm-header-container > .oxd-button').should('be.visible')
      .and('be.enabled')
      .click()
    cy.get('.--name-grouped-field > :nth-child(1) > :nth-child(2) > .oxd-input', {timeout: 5000}).should('be.visible')
      .and('be.enabled')
      .type(cadastropim.cadastroValido.primeiroNome)
    cy.get(':nth-child(3) > :nth-child(2) > .oxd-input', {timeout: 5000}).should('be.visible')
      .and('be.enabled')
      .type(cadastropim.cadastroValido.ultimoNome)
      cy.get('.oxd-grid-item > .oxd-input-group > :nth-child(2) > .oxd-input', {timeout: 5000}).should('be.visible')
      .and('be.enabled')
      .clear()
    cy.get('.oxd-grid-item > .oxd-input-group > :nth-child(2) > .oxd-input', {timeout: 5000}).should('be.visible')
      .and('be.enabled')
      .type(cadastropim.cadastroValido.id)
    cy.get('.oxd-button--secondary').as('clickSave').should('be.visible')
      .and('be.enabled')
      .click()
    cy.get('.oxd-toast').should('not.be.disabled')
      .and('contain', 'Successfully')
  })


    it('Teste deve pesquisar um usuário pelo nome corretamente', () => {
    cy.get(':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-autocomplete-wrapper > .oxd-autocomplete-text-input > input').should('be.visible')
      .and('be.enabled')
      .type(cadastropim.search.primeiroNome)
    cy.get('.oxd-form-actions > .oxd-button--secondary').as('Search').should('be.visible')
      .and('be.enabled')
      .click()
    cy.get('.oxd-table-card > .oxd-table-row').should('not.be.disabled')
      .and('contain', cadastropim.delete.id)
    cy.get('.oxd-table-card > .oxd-table-row').should('not.be.disabled')
      .and('contain', cadastropim.delete.primeiroNome)
    cy.get('.oxd-table-card > .oxd-table-row').should('not.be.disabled')
      .and('contain', cadastropim.delete.ultimoNome)
  })

  it('Teste deve excluir um usuário corretamente', () => {
    cy.get(':nth-child(2) > .oxd-input').should('be.visible')
      .and('be.enabled')
      .type(cadastropim.search.id)
    cy.get('.oxd-form-actions > .oxd-button--secondary').should('be.visible')
      .and('be.enabled')
      .click()
    cy.wait(1000)
    cy.get('.oxd-table-card > .oxd-table-row').should('not.be.disabled')
      .and('contain', cadastropim.delete.id)
    cy.get('.oxd-table-card > .oxd-table-row').should('not.be.disabled')
      .and('contain', cadastropim.delete.primeiroNome)
    cy.get('.oxd-table-card > .oxd-table-row').should('not.be.disabled')
      .and('contain', cadastropim.delete.ultimoNome)
    cy.wait(1000)
    cy.get('.oxd-table-cell-actions > :nth-child(2)').should('be.visible')
      .and('be.enabled')
      .click()
    cy.get('.oxd-button--label-danger').should('be.visible')
      .and('be.enabled')
      .click()
    cy.get('.oxd-toast').should('not.be.disabled')
      .and('contain', 'Successfully')
  })
})
